apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-beat
  namespace: dify
  labels:
    app.kubernetes.io/name: worker-beat
    app.kubernetes.io/part-of: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker-beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker-beat
        app.kubernetes.io/part-of: dify
    spec:
      containers:
        - name: worker-beat
          image: langgenius/dify-api:1.13.0
          envFrom:
            - configMapRef:
                name: dify-shared-config
          env:
            - name: MODE
              value: "beat"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: REDIS_PASSWORD
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: CELERY_BROKER_URL
            - name: WEAVIATE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: WEAVIATE_API_KEY
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: RESEND_API_KEY
            - name: PLUGIN_DAEMON_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: PLUGIN_DAEMON_KEY
          resources:
            requests:
              memory: "320Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "500m"
