apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-daemon
  namespace: dify
  labels:
    app.kubernetes.io/name: plugin-daemon
    app.kubernetes.io/part-of: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plugin-daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plugin-daemon
        app.kubernetes.io/part-of: dify
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - plugin-daemon
              topologyKey: kubernetes.io/hostname
      containers:
        - name: plugin-daemon
          image: langgenius/dify-plugin-daemon:0.5.3-local
          ports:
            - containerPort: 5002
              name: http
            - containerPort: 5003
              name: debug
          envFrom:
            - configMapRef:
                name: dify-shared-config
          env:
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: DB_PLUGIN_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: REDIS_PASSWORD
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_DAEMON_PORT
            - name: SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: PLUGIN_DAEMON_KEY
            - name: MAX_PLUGIN_PACKAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_MAX_PACKAGE_SIZE
            - name: PPROF_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_PPROF_ENABLED
            - name: DIFY_INNER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_DIFY_INNER_API_URL
            - name: DIFY_INNER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: PLUGIN_DIFY_INNER_API_KEY
            - name: PLUGIN_REMOTE_INSTALLING_HOST
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_DEBUGGING_HOST
            - name: PLUGIN_REMOTE_INSTALLING_PORT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_DEBUGGING_PORT
            - name: PLUGIN_WORKING_PATH
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_WORKING_PATH
            - name: FORCE_VERIFYING_SIGNATURE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: FORCE_VERIFYING_SIGNATURE
            - name: PYTHON_ENV_INIT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_PYTHON_ENV_INIT_TIMEOUT
            - name: PLUGIN_MAX_EXECUTION_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_MAX_EXECUTION_TIMEOUT
            - name: PLUGIN_STDIO_BUFFER_SIZE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_STDIO_BUFFER_SIZE
            - name: PLUGIN_STDIO_MAX_BUFFER_SIZE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_STDIO_MAX_BUFFER_SIZE
            - name: PIP_MIRROR_URL
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PIP_MIRROR_URL
            - name: PLUGIN_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_STORAGE_TYPE
            - name: PLUGIN_STORAGE_LOCAL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_STORAGE_LOCAL_ROOT
            - name: PLUGIN_INSTALLED_PATH
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_INSTALLED_PATH
            - name: PLUGIN_PACKAGE_CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_PACKAGE_CACHE_PATH
            - name: PLUGIN_MEDIA_CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_MEDIA_CACHE_PATH
            - name: SENTRY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_SENTRY_ENABLED
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: dify-shared-config
                  key: PLUGIN_SENTRY_DSN
          volumeMounts:
            - name: plugin-daemon-storage
              mountPath: /app/storage
          resources:
            requests:
              memory: "1536Mi"
              cpu: "50m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: plugin-daemon-storage
          persistentVolumeClaim:
            claimName: plugin-daemon-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-daemon
  namespace: dify
  labels:
    app.kubernetes.io/name: plugin-daemon
    app.kubernetes.io/part-of: dify
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      name: http
    - port: 5003
      targetPort: 5003
      name: debug
  selector:
    app.kubernetes.io/name: plugin-daemon
