apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dify

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secrets.yaml
  - 03-pvc.yaml
  - 10-postgres.yaml
  - 11-redis.yaml
  - 12-weaviate.yaml
  - 13-sandbox.yaml
  - 14-ssrf-proxy.yaml
  - 20-api.yaml
  - 21-worker.yaml
  - 22-worker-beat.yaml
  - 23-web.yaml
  - 24-plugin-daemon.yaml
  - 30-nginx.yaml
  - 31-ingress.yaml
  - 40-external-service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.13.0"
